FROM node:20-bookworm

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN pip3 install --break-system-packages pymupdf

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/main.js"]